#!/bin/sh

card=$(grep -oP '(?<=defaults.pcm.card ).*' /etc/asound.conf)
options="-o hw:$card"
echo "Your Sound Card Number:" $card
sed -i "s|-o default|$options|g" /opt/sq/sq.service

# wget -O - https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/change-sq | sh
