#!/bin/sh

if [ -d "/opt/sq" ]; then
    echo "Stopping Squeezelite"
    systemctl stop sq.service
fi

cd /tmp
wget https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/sq.service
wget https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/sq.sh
cp -f /tmp/sq.service /opt/sq/
cp -f /tmp/sq.sh /opt/sq/
chmod -R 755 /opt/sq/sq.service
chmod -R 755 /opt/sq/sq.sh


#echo "Download Squeezelite 1.9.9.1422"
#wget https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/squeezelite64.tar.gz
#cp -f /opt/sq/squeezelite64 /opt/sq/squeezelite64.backup
#tar -xzf squeezelite64.tar.gz --overwrite -C /

systemctl daemon-reload
systemctl restart sq.service
echo "Finished"
systemctl status sq.service
